services:
  # =========================
  # Vector Database
  # =========================

  qdrant:
    image: qdrant/qdrant:v1.16.2
    container_name: eduai-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  # =========================
  # Backend API + Pipelines
  # =========================
  eduai-backend:
    build:
      context: ./backend
    container_name: eduai-backend
    depends_on:
      - qdrant
    ports:
      - "8011:8011"
    env_file:
      - .env
    environment:
      EDUAI_DATA_BASE_PATH: /data
    volumes:
      - eduai_data:/data
    restart: unless-stopped


  # =========================
  # Streamlit Test Frontend
  # =========================
  eduai-frontend:
    env_file:
      - .env
    build:
      context: ./frontend/streamlit
    container_name: eduai-frontend
    depends_on:
      - eduai-backend
    ports:
      - "8501:8501"
    volumes:
      - ./backend:/app/backend
      - eduai_data:/data
    restart: unless-stopped

# =========================
# Volumes
# =========================
volumes:
  eduai_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mac/Library/CloudStorage/SynologyDrive-education
  qdrant_data:
