services:
  # =========================
  # Vector Database
  # =========================

  qdrant:
    image: qdrant/qdrant:v1.16.2
    container_name: eduai-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  # =========================
  # Backend API + Pipelines
  # =========================
  eduai-backend:
    build:
      context: ./backend
    container_name: eduai-backend
    depends_on:
      - qdrant
    ports:
      - "8011:8011"
    env_file:
      - .env
    environment:
      EDUAI_DATA_BASE_PATH: /data
      # Mặc định Qdrant khi chạy Docker (không chọn gì = eduai-qdrant:6333)
      QDRANT_HOST: eduai-qdrant
      QDRANT_PORT: "6333"
    volumes:
      - eduai_data:/data
      # Mount source for hot-reload when developing
      - ./backend/src:/app/src
    command: uvicorn eduai.main:app --host 0.0.0.0 --port 8011 --reload
    restart: unless-stopped


  # =========================
  # Streamlit Test Frontend
  # =========================
  eduai-frontend:
    env_file:
      - .env
    build:
      context: ./frontend/streamlit
    container_name: eduai-frontend
    depends_on:
      - eduai-backend
    ports:
      - "8012:8012"
    volumes:
      - ./backend:/app/backend
      - eduai_data:/data
    restart: unless-stopped

# =========================
# Volumes
# =========================
volumes:
  eduai_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mac/Library/CloudStorage/SynologyDrive-research
  qdrant_data:
